POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0xfa2",
    "operation":"createVehicle",
    "data": {
        "image": "https://www.kickassfacts.com/wp-content/uploads/2021/04/bear.jpg",
        "attributes":{ 
            "bruh": "bruh"
        },
        "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    }
}

###

POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0xfa2",
    "operation":"destroyVehicle",
    "data": {
        "tokenId": 12,
        "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    }
}

###

POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0xfa2",
    "operation":"concludeAuction",
    "data": {
        "tokenId": 7,
        "price":"358107188643704830",
        "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    }
}

###

GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0xfa2",
    "operation":"isAuction",
    "data": {
        "tokenId": 7
    }
}