
#MINT 
POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0x13881",
    "operation":"createVehicle",
    "data": {
        "image": "https://www.tesla.com/ownersmanual/images/GUID-999EC68D-FD44-4237-8AB8-AB97A724F3B0-online-en-US.png",
        "attributes": {
            "company": "Tesla",
            "model": "X",
            "vhcid": "Tesla29482032103102",
            "year": "2020",
            "color": "Black",
            "body": "Hatchback",
            "transmission": "Automatic",
            "fuel": "Electric",
            "engine": "Dual Motor AWD 60D",
            "doors": "5",
            "seats": "7",
            "driver_side": "Left"
        },
        "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    }
}

###
#BURN
POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0xfa2",
    "operation":"destroyVehicle",
    "data": {
        "tokenId": 7,  
        "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    }
}

###
#LIST FOR SALE
POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0xfa2",
    "operation":"listForSale",
    "data": {
        "tokenId": 4,
        "price":"358107188643704830",
        "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    }
}


###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0xfa2",
    "operation":"isForSale",
    "data": {
        "tokenId": 4
    }
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0xfa2",
    "operation":"hasRole",
    "data": {
        "role": "6f75c7e45b923a976102cf1173921af9cd14f3a7474f743b14e64b348aa2520d",
        "account": "0x41F71840346605b60B12CCaa19f7842c869f0095"
    }
}