
#MINT 
POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0x4",
    "operation":"mint",
    "data": {
        "image": "https://cdn.pocket-lint.com/r/s/970x/assets/images/144304-cars-review-tesla-model-x-review-lead-image1-vdycmknzck-jpg.webp",
        "attributes": {
            "company": "Tesla",
            "model": "Model X",
            "vhcid": "Tesla29482032103102",
            "year": "2020",
            "color": "Black",
            "body": "Hatchback",
            "transmission": "Automatic",
            "fuel": "Electric",
            "engine": "AWD 60D",
            "doors": "5",
            "seats": "7",
            "driver_side": "Left"
        }
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#BURN
POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0xfa2",
    "operation":"destroyVehicle",
    "data": {
        "tokenId": 0
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#LIST FOR SALE
POST https://localhost:8443/
Content-Type: application/json

{   
    "chain":"0x4",
    "operation":"listInstant",
    "data": {
        "tokenId": 0,
        "price":"358107188643704830"
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}



###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"tokenURI",
    "data": {
        "tokenId": "0"
    }
}


###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"isForSale",
    "data": {
        "tokenId": 0
    }
}


###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"hasRole",
    "data": {
        "role": "ODOMETER_ROLE",
        "address": "0xBD24d8ab73E92a1ebA8E0Db97A20671b9713191a"
    }
}

###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"grantRole",
    "data": {
        "role": "ODOMETER_ROLE",
        "address": "0xBD24d8ab73E92a1ebA8E0Db97A20671b9713191a"
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
    
}

###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"revokeRole",
    "data": {
        "role": "GARAGE_ROLE",
        "address": "0xBD24d8ab73E92a1ebA8E0Db97A20671b9713191a"
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"getApprovedGarage",
    "data": {
        "tokenId": "0"
    }
}

###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"setApprovedGarage",
    "data": {
        "tokenId": "0",
        "addr": "0xBD24d8ab73E92a1ebA8E0Db97A20671b9713191a"
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"getOdometerValue",
    "data": {
        "tokenId": "0"
    }
}

###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"increaseOdometer",
    "data": {
        "tokenId": "0",
        "value": "1"
    },
    "private_key": "ceddfa13d00d47e636b7f36203d29197c4f9b3a0b47766ba5e8bf214ede7daff"
}


###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"setOdometerAddress",
    "data": {
        "tokenId": "0",
        "address": "0xBD24d8ab73E92a1ebA8E0Db97A20671b9713191a"
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "operation":"getNetworkTables"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "operation":"getContract"
}


###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"setPullCache",
    "data": {
        "value": true
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "operation":"getContract",
    "contract":"Management.json"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"restart",
    "data": {
    }
}

###
#ANY GET
POST https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"setRestart",
    "data": {
        "value": true
    },
    "private_key": "3e4f26cb570f3db2f744b90862882578f5bce24b10de35ad947bf13b0c3ccebd"
}

###
#ANY GET
GET https://localhost:8443/
Content-Type: application/json

{
    "chain":"0x4",
    "operation":"getRestart",
    "data": {
    }
}